### PR TITLE
Support listen only App Links

### PR DESCRIPTION
**Pull request by ho-doan**

### CODE REVIEW

**Comment by ho-doan** [comment]
We expect dynamic_link and app link to run independently during this period

**Comment by nambv** [comment]
hi @ho-doan-ominext, thanks a lot for your contribution.
is it working with branch.io too? Current it overrides the branch.io subscription so that all incoming branch.io link go directly to app links

**Comment by ho-doan-ominext** [comment]
hi @nambv, This case is only true when using both firebase_dynamic_links and app_links, to avoid the situation where both app_links and firebase_dynamic_link listen to the same event.

**Comment by nambv** [comment]
got it, thanks a lot @ho-doan

**Pull request closed without merging**
