### PR TITLE
feat: support deeplink on Linux platform

### PR DESCRIPTION
**Pull request by LucasXu0**
- Support deeplink on Linux platform.

For more details, please refer to this [issue](https://github.com/llfbandit/app_links/issues/20).

### CODE REVIEW

**Comment by llfbandit** [comment]
Many thanks to bring linux support to this package.
Seems good to me.

Could you update the README.md by adding a howto setup on this platform?

**Comment by LucasXu0** [comment]
> Could you update the README.md by adding a howto setup on this platform?

Sure. Will update this PR asap.

**Comment by liquidiert** [comment]
@LucasXu0 would also really love to see this in the app_links package!

**Comment by TekExplorer** [comment]
Out of curiosity, what is the purpose of that
```diff
- TRUE
+ FALSE
```

**Comment by TekExplorer** [comment]
Also consider using \```patch instead of ```xml for formatting

**Comment by LucasXu0** [comment]
> Out of curiosity, what is the purpose of that
> 
> ```diff
> - TRUE
> + FALSE
> ```

Return FALSE to allow the package to handle the command line.

**Comment by TekExplorer** [comment]
> Return FALSE to allow the package to handle the command line.
Ah, but will we still be able to handle command line args normally if we wanted to?

**Comment by LucasXu0** [comment]
What do you mean "handle command line args normally"?

**Comment by llfbandit** [comment]
I guess he wanted to know if modifying the return result or just applying the plugin would conflict with other command line processing.
But you already answered to this in your previous comment.
The purpose of the modifications are about getting all command line parameters.

**Comment by TekExplorer** [comment]
> But you already answered to this in your previous comment.

...no?

> What do you mean "handle command line args normally"?

I mean, if i currently parse command line parameters ie, `myApp --login username:password` will this interfere with that? And if it does, is there a method to get around it?

**Comment by LucasXu0** [comment]
> > But you already answered to this in your previous comment.
> 
> 
> 
> ...no?
> 
> 
> 
> > What do you mean "handle command line args normally"?
> 
> 
> 
> I mean, if i currently parse command line parameters ie, `myApp --login username:password` will this interfere with that? And if it does, is there a method to get around it?

I'm not sure. I suggest you can give it a try by checking out this PR.

**Comment by liquidiert** [comment]
@LucasXu0 @llfbandit @TekExplorer I just tried with @LucasXu0s branch and command line args can still be parsed after setting line 88 to FALSE 👍

**Pull request merged**
