### PR TITLE
fix(iOS): Return true in NSUserActivityTypeBrowsingWeb to indicate that app links handled the activity

### LINKED ISSUE #96: GoRouter and AppLinks uriLinkStream both attempt to handle the universal link route (iOS issue only)
**Describe the bug**

I am using AppLinks in conjunction with GoRouter in my flutter app. My current setup works as expected while testing on the Android version of my flutter app, however I'm getting some unexpected behavior while testing on the iOS flutter app.

In iOS when I click a link that is from one of my associated domains defined in the iOS app capabilities, the AppLinks uriLinkStream listener that I have set up DOES trigger in response to the url (as expected). However, at the same time, my GoRouter attempts to navigate to this route (which is not defined as a supported route in the GoRouter configuration) and throws an error on the screen saying 
`Exception: Match error found during build has Exception: no routes for location`

Is there a way to prevent the GoRouter from handling the route so that only AppLinks handles it? Again, this is only a problem in iOS and does not behave this way on Android. Therefore, I'm wondering if I have my custom app delegate setup incorrectly in the iOS app configuration. Here's what I have currently for my custom app delegate:
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[X] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[X] Yes  
[ ] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[X] Yes  
[ ] No  
[ ] Irrelevant here

### PR DESCRIPTION
**Pull request by AlexHodges13**
fixes #96

### CODE REVIEW

**Comment by AlexHodges13** [comment]
@llfbandit could you please review/merge this PR at your earliest convenience?
Thanks in advance!

**Comment by AlexHodges13** [comment]
@llfbandit Could you please review/merge this PR or grant me privileges to do so? This is an open defect in my production app that I need to get resolved!

**Comment by llfbandit** [comment]
Closing this to provide a breaking change notice. v5 will be released soon. Thanks for your contribution.

**Comment by intervall-mohammed** [comment]
Can we please get this merged in anyway? I've had to apply this change to fix an issue with our app where pressing on a link would (correctly) open the app, and then immediately also open the same link in Safari.

(the `app_links` version was 6.2.1, and there don't seem to have been any iOS-related changes since then)

**Comment by llfbandit** [comment]
No, the package provides now everything you need to handle it by yourself. Read the docs.

**Pull request closed without merging**
