### PR TITLE
feat(OHOS): Add HarmonyOS platform support

### PR DESCRIPTION
**Pull request by Mr-Gargantua**
Add HarmonyOS platform support, based on oh-3.22.3.

### CODE REVIEW

**Comment by llfbandit** [comment]
Is this PR finished?
If os, how is it related to this package? because there's no binding to root package. Also, Flutter does not support HarmonyOS so...

**Comment by Mr-Gargantua** [comment]
It’s already finished, and I have tested it. By "root package," do you mean `app_links`?  
`app_links_ohos` implements the `app_links_platform_interface` interface, but it’s a customized version of Flutter by Huawei (oh-3.22.3). Therefore, it’s not included as a dependency in the root package (`app_links`). If developers want to use it, they need to add the dependency `app_links_ohos: ^1.0.0` separately.

**Comment by llfbandit** [comment]
https://pub.dev/packages/app_links_ohos already exists... And I don't understand why you want to merge in this repository. I won't be able to support it.
You can publish your HOS package by yourself, this is why platform interface exists.

**Comment by Mr-Gargantua** [comment]
Okay. I didn’t notice this existed before… I’ll close it then.

**Pull request closed without merging**
